######################## Paper Information ########################################
# Personal info
paper_name: CRIMSON: Compute-intensive loop acceleration by Randomized Iterative Modulo Scheduling and Optimized Mapping on CGRAs

organization: IEEE
# sub_organization: School of Computing and Augmented Intelligence 


######################## Paper Resources ########################################

paper_pdf: https://mpslab-asu.github.io/publications/papers/Balasubramanian2020TCAD.pdf
# supplementary_pdf: Supplementary PDF here
# code: https://github.com/MPSLab-ASU/Project_Page_Template
# arXiv : https://arxiv.org/abs/1512.01274
IEEE: https://ieeexplore.ieee.org/document/9187262
# Additional icon links

# favicon: assets/images/MPS_Lab.ico

main_media:
  source: assets/images/figure1.png
  caption: A typical CGRA architecture consisting of 4x4 PEs connected in a 2D mesh. Every cycle, each PE gets an instruction from the Instruction Memory, and can operate on the outputs of neighboring PEs and/or the Data Memory



######################## DO NOT EDIT BELOW THIS LINE ########################################

# Footer
footer_show_references: true

#sass
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript


markdown: kramdown
permalink: pretty

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  "README.md",
  ]
